### ISSUE TITLE
predict.FFTrees() does not work with a data argument unless it is just an object name

### ISSUE THREAD

**Issue by stephlocke** [ndphillips/FFTrees#19] opened 2017-06-22 14:06 UTC
When I run a predict on a partial dataset I get an error - this doesn't happen for other predict methods suggesting it's a specific implementation issue. Would you be able to take a look?

```
library(FFTrees)

# Works
resultsfull<-predict(FFTrees(survived ~., titanic),data=titanic)
resultsglm<-predict(glm(survived ~., data=titanic),data=titanic[1:10,])

# Errors
resultssubset<-predict(FFTrees(survived ~., titanic),data=titanic[1:10,])
## Error in data.frame(n = N, hi = hi, mi = mi, fa = fa, cr = cr, sens = sens,  : 
##  object 'wacc' not found
```

```
> sessionInfo()
R version 3.4.0 Patched (2017-04-28 r72639)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] FFTrees_1.2.3

loaded via a namespace (and not attached):
 [1] igraph_1.0.1         Rcpp_0.12.11         magrittr_1.5        
 [4] colorspace_1.3-2     lattice_0.20-35      jpeg_0.1-8          
 [7] pbapply_1.3-2        stringr_1.2.0        BayesFactor_0.9.12-2
[10] yarrr_0.1.5          tools_3.4.0          parallel_3.4.0      
[13] grid_3.4.0           packrat_0.4.8-1      circlize_0.4.0      
[16] e1071_1.6-8          coda_0.19-1          MatrixModels_0.4-1  
[19] class_7.3-14         gtools_3.5.0         randomForest_4.6-12 
[22] Matrix_1.2-10        GlobalOptions_0.0.12 rpart_4.1-11        
[25] shape_1.4.2          stringi_1.1.5        compiler_3.4.0      
[28] mvtnorm_1.0-6  
```

**Comment by ndphillips** [comment] 2017-06-22 14:16
I think the problem is that `titanic[1:10,]` has no variance in the cues or the criterion (I just double checked).

I just tried with `resultssubset<-predict(FFTrees(survived ~., titanic),data=titanic[sample(nrow(titanic), 10),])` and it worked.

Can you confirm on your end?

**Comment by stephlocke** [comment] 2017-06-22 15:08
Yeah that works but I'm not sure why I need to pass data with variance? 

My (perhaps naive) assumption is that when I pass data to the predict function it gives me the outcomes using the model object - if I pass one record (using the tree for on the fly classification) then my variance is always going to be 0 so I wouldn't be able to use predict.FFTree like I use other predict methods.

**Comment by ndphillips** [comment] 2017-06-22 15:14
Ah now I see your point! I thought the trees were being trained on data with no variance. Of course, one should be able to predict data with no variance. Let me try to track this down...

**Comment by stephlocke** [comment] 2017-06-22 15:17
Thanks :D 
And it's a great package btw - I'm using FFTrees instead of rpart for intro to to stats in r because of the awesome viz and simple to understand trees

**Comment by stephlocke** [comment] 2017-06-22 15:28
Sure thing - I've can workaround by putting the 10 rows into a variable first so it's a not blocker :)

**Comment by ndphillips** [comment] 2017-06-24 10:52
Ok I think I fixed it! Please try reinstalling from GitHub and see if it works on your end too. Thanks for catching this!

**Comment by ndphillips** [comment] 2017-06-28 12:24
@stephlocke  I'll close this for now as I'm pretty sure it's fixed, but if you're still having problems please reopen it.

Thanks again for posting the issue!

**Closed by ndphillips** 2017-06-28 12:24 UTC
